### ISSUE TITLE
Trained model and train_im0.txt missing

### ISSUE THREAD

**Issue by alexzzhu** [ryersonvisionlab/unsupFlownet#1]
The data loader in util/TrainingData.py looks like it relies on two text files to read the paths to the images. Is it possible to have that available somewhere, along with a trained model?

Thanks!

**Comment by JasonYuJjyu** [comment]
An example of the data lists was originally included under [example_data](https://github.com/ryersonvisionlab/unsupFlownet/tree/master/example_data) for a small dataset of 1 image pair.

The repo has been [updated](https://github.com/ryersonvisionlab/unsupFlownet/tree/54f0d0d1f36f6cdad506de246b19c8dee5b41e2a) to contain a new [example](https://github.com/ryersonvisionlab/unsupFlownet/tree/master/example_data/datalists2) data list used for KITTI. A pre-trained model can now be downloaded through the [download scripts](https://github.com/ryersonvisionlab/unsupFlownet/tree/master/model_download_scripts). Additional details about these additions are available on the [README](https://github.com/ryersonvisionlab/unsupFlownet/blob/master/README.md)

**Comment by alexzzhu** [comment]
Thanks!
