### ISSUE TITLE
Model downloading script doesn't work

### ISSUE THREAD

**Issue by CathIAS** [ryersonvisionlab/unsupFlownet#2]
**download_model_weights.sh** won't download. I cannot open the link because I do not have the authorization to do so.

**Comment by JasonYuJjyu** [comment]
Sorry about that. The script has been updated to provide a link to manually download the weights from google drive.

**Comment by CathIAS** [comment]
The new link says file doesn't exist.

**Comment by JasonYuJjyu** [comment]
I've checked the link it provides and it works. Here is the link it gives for your reference: https://drive.google.com/file/d/18MXPbjXUnGG_Fcij8YUs6mtyQcBwnSru/view?usp=sharing

**Comment by CathIAS** [comment]
This works. I see. It's when copy paste from terminal it gives an extra symbol over the line break. Thank you.
